// random value generated by computer
var comp = Math.floor(Math.random() * 100 + 1);

var num_guess = 1;

document.getElementById("submitguess").onclick = function () {

    // user input
    var userGuess = document.getElementById("guessField").value;

    if (userGuess == comp) {
        // writing into HTML file using DOM
        document.getElementById("result").innerHTML += `HURRAYYYYYYY, you guessed it CORRECT 😃😃😃. You took ${num_guess} attempts <br>.`

    } else if (userGuess > comp) {
        num_guess++;
        document.getElementById("result").innerHTML += "Try entering a SMALLER number ⬇️⬇️⬇️ <br>"

    } else {
        num_guess++;
        document.getElementById("result").innerHTML += "Try entering a GREATER number ⬆️⬆️⬆️ <br>"
    }
}
